In [1]:
!pip install opendatasets

In [2]:
import opendatasets as od

In [3]:
od.download("https://www.kaggle.com/datasets/arunrk7/surface-crack-detection")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: ajaysharmainsideaiml
Your Kaggle Key: ··········


100%|██████████| 233M/233M [00:02<00:00, 94.9MB/s]


In [6]:
import os
negativeimages = os.listdir("/content/surface-crack-detection/Negative/")

In [8]:
len(negativeimages)

20000

In [9]:
negativeimages = negativeimages[:5000]

In [10]:
len(negativeimages)

5000

In [12]:
images = []
labels = []
for image in negativeimages:
  print(image)
  print("===")

Streaming output truncated to the last 5000 lines.
18626.jpg
===
13988.jpg
===
00661.jpg
===
06100.jpg
===
14911.jpg
===
13190.jpg
===
16105.jpg
===
08528.jpg
===
07309.jpg
===
18748.jpg
===
17004.jpg
===
17201.jpg
===
11573.jpg
===
13813.jpg
===
11547.jpg
===
08317.jpg
===
05900.jpg
===
00495.jpg
===
02302.jpg
===
04625.jpg
===
05000.jpg
===
01577.jpg
===
08638.jpg
===
12310.jpg
===
18897.jpg
===
16450.jpg
===
15327.jpg
===
14882.jpg
===
10780.jpg
===
13733.jpg
===
18395.jpg
===
16222.jpg
===
05938.jpg
===
02679.jpg
===
18309.jpg
===
05279.jpg
===
17087.jpg
===
02609.jpg
===
18275.jpg
===
16329.jpg
===
16395.jpg
===
08478.jpg
===
11301.jpg
===
15290.jpg
===
06420.jpg
===
11831.jpg
===
17603.jpg
===
00445.jpg
===
11349.jpg
===
07839.jpg
===
06470.jpg
===
15944.jpg
===
08925.jpg
===
10799.jpg
===
05798.jpg
===
04406.jpg
===
04637.jpg
===
17806.jpg
===
06209.jpg
===
07988.jpg
===
05220.jpg
===
04119.jpg
===
18068.jpg
===
06769.jpg
===
00057.jpg
===
14656.jpg
===
14762.jpg
===
01485.jpg
=

In [13]:
images = []
labels = []
negative_images_folder_path = "/content/surface-crack-detection/Negative/"
for image in negativeimages:
  img_path = os.path.join(negative_images_folder_path, image)
  print(img_path)
  print("===")

Streaming output truncated to the last 5000 lines.
/content/surface-crack-detection/Negative/18626.jpg
===
/content/surface-crack-detection/Negative/13988.jpg
===
/content/surface-crack-detection/Negative/00661.jpg
===
/content/surface-crack-detection/Negative/06100.jpg
===
/content/surface-crack-detection/Negative/14911.jpg
===
/content/surface-crack-detection/Negative/13190.jpg
===
/content/surface-crack-detection/Negative/16105.jpg
===
/content/surface-crack-detection/Negative/08528.jpg
===
/content/surface-crack-detection/Negative/07309.jpg
===
/content/surface-crack-detection/Negative/18748.jpg
===
/content/surface-crack-detection/Negative/17004.jpg
===
/content/surface-crack-detection/Negative/17201.jpg
===
/content/surface-crack-detection/Negative/11573.jpg
===
/content/surface-crack-detection/Negative/13813.jpg
===
/content/surface-crack-detection/Negative/11547.jpg
===
/content/surface-crack-detection/Negative/08317.jpg
===
/content/surface-crack-detection/Negative/05900.jpg
=

In [14]:
import cv2
images = []
labels = []
negative_images_folder_path = "/content/surface-crack-detection/Negative/"
for image in negativeimages:
  img_path = os.path.join(negative_images_folder_path, image)
  img = cv2.imread(img_path)
  img = cv2.resize(img, (64,64))
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  images.append(img)
  labels.append(0)

In [15]:
import os
positiveimages = os.listdir("/content/surface-crack-detection/Positive/")
positiveimages = positiveimages[:5000]
positive_images_folder_path = "/content/surface-crack-detection/Positive/"
for image in positiveimages:
  img_path = os.path.join(positive_images_folder_path, image)
  img = cv2.imread(img_path)
  img = cv2.resize(img, (64,64))
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  images.append(img)
  labels.append(1)

In [17]:
len(images)

10000

In [37]:
len(labels)

10000

In [19]:
import numpy as np

images = np.array(images)
labels = np.array(labels)

In [21]:
# images

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
xtrain,xtest,ytrain,ytest = train_test_split(images,labels,test_size = 0.2, random_state=53)

In [24]:
xtrain.shape

(8000, 64, 64, 3)

In [25]:
xtest.shape

(2000, 64, 64, 3)

In [26]:
xtrain

array([[[[171, 167, 155],
         [149, 145, 133],
         [153, 149, 140],
         ...,
         [155, 152, 145],
         [163, 160, 153],
         [167, 164, 159]],

        [[150, 146, 134],
         [157, 153, 141],
         [150, 146, 137],
         ...,
         [164, 161, 154],
         [168, 165, 158],
         [167, 164, 159]],

        [[150, 146, 134],
         [151, 147, 135],
         [162, 158, 149],
         ...,
         [164, 161, 154],
         [161, 158, 151],
         [158, 154, 149]],

        ...,

        [[148, 146, 134],
         [146, 144, 132],
         [150, 148, 137],
         ...,
         [160, 160, 151],
         [149, 149, 142],
         [146, 146, 138]],

        [[154, 153, 140],
         [151, 149, 137],
         [149, 147, 135],
         ...,
         [154, 154, 146],
         [146, 146, 138],
         [145, 145, 138]],

        [[149, 147, 135],
         [151, 150, 138],
         [156, 154, 142],
         ...,
         [147, 147, 142],
        

In [27]:
xtrain = xtrain / 255.0

In [29]:
xtrain

array([[[[0.67058824, 0.65490196, 0.60784314],
         [0.58431373, 0.56862745, 0.52156863],
         [0.6       , 0.58431373, 0.54901961],
         ...,
         [0.60784314, 0.59607843, 0.56862745],
         [0.63921569, 0.62745098, 0.6       ],
         [0.65490196, 0.64313725, 0.62352941]],

        [[0.58823529, 0.57254902, 0.5254902 ],
         [0.61568627, 0.6       , 0.55294118],
         [0.58823529, 0.57254902, 0.5372549 ],
         ...,
         [0.64313725, 0.63137255, 0.60392157],
         [0.65882353, 0.64705882, 0.61960784],
         [0.65490196, 0.64313725, 0.62352941]],

        [[0.58823529, 0.57254902, 0.5254902 ],
         [0.59215686, 0.57647059, 0.52941176],
         [0.63529412, 0.61960784, 0.58431373],
         ...,
         [0.64313725, 0.63137255, 0.60392157],
         [0.63137255, 0.61960784, 0.59215686],
         [0.61960784, 0.60392157, 0.58431373]],

        ...,

        [[0.58039216, 0.57254902, 0.5254902 ],
         [0.57254902, 0.56470588, 0.51764706]

In [38]:
xtest.shape

(2000, 64, 64, 3)

In [30]:
xtest = xtest / 255.0

In [32]:
from tensorflow.keras.models import Sequential

In [36]:
model = Sequential() # brain without neurons

In [35]:
from tensorflow.keras.layers import Dense,Conv2D, MaxPooling2D, Flatten
#Conv2D KERNELS LAYERS
#MaxPooling2D MAXPOOLING LAYERS
#Flatten MATRIX => 1D ARRAY(1D VECTOR)

In [39]:
model.add(Conv2D(32,(3,3), activation = 'relu', input_shape = (64,64,3))) #INPUT LAYER
model.add(MaxPooling2D(2,2))
# first cnn block

In [40]:
model.add(Conv2D(64,(3,3), activation = 'relu'))
model.add(MaxPooling2D(2,2))
# 2nd cnn block

In [42]:
model.add(Conv2D(64,(3,3), activation = 'relu'))
model.add(MaxPooling2D(2,2))

# 3rd cnn block

In [43]:
model.add(Conv2D(64,(3,3), activation = 'relu'))

In [44]:
model.add(Flatten())
#ann
model.add(Dense(64, activation = "relu")) #fcl
model.add(Dense(1,activation = "sigmoid")) #output layer

In [47]:
model.compile(optimizer = "adam", loss = "binary_crossentropy" , metrics = ["accuracy"])

In [48]:
model.fit(xtrain,ytrain, epochs = 3 , batch_size = 32 ,validation_data = (xtest,ytest))

Epoch 1/3
250/250 [==============================] - 59s 229ms/step - loss: 0.1550 - accuracy: 0.9401 - val_loss: 0.0650 - val_accuracy: 0.9830
Epoch 2/3
250/250 [==============================] - 53s 212ms/step - loss: 0.0657 - accuracy: 0.9803 - val_loss: 0.0350 - val_accuracy: 0.9890
Epoch 3/3
250/250 [==============================] - 53s 212ms/step - loss: 0.0452 - accuracy: 0.9850 - val_loss: 0.0363 - val_accuracy: 0.9900


In [53]:
import cv2
import numpy as np

img_path = "/content/surface-crack-detection/Negative/00003.jpg"
image = cv2.imread(img_path)
image = cv2.resize(image,(64,64))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

In [50]:
image.shape

(64, 64, 3)

In [54]:
image

array([[[157, 154, 149],
        [160, 158, 152],
        [186, 183, 178],
        ...,
        [192, 189, 184],
        [192, 189, 184],
        [189, 185, 182]],

       [[159, 156, 151],
        [165, 162, 157],
        [181, 178, 173],
        ...,
        [195, 193, 187],
        [192, 189, 184],
        [192, 188, 185]],

       [[141, 138, 133],
        [168, 165, 160],
        [174, 171, 166],
        ...,
        [183, 180, 175],
        [173, 170, 165],
        [188, 184, 181]],

       ...,

       [[189, 184, 180],
        [191, 186, 182],
        [171, 166, 162],
        ...,
        [170, 167, 162],
        [171, 169, 164],
        [208, 205, 200]],

       [[213, 208, 204],
        [216, 211, 207],
        [168, 163, 159],
        ...,
        [178, 175, 170],
        [179, 176, 171],
        [167, 164, 159]],

       [[172, 167, 163],
        [205, 200, 196],
        [174, 169, 165],
        ...,
        [180, 176, 173],
        [184, 180, 177],
        [175, 171, 168]]

In [55]:
image = np.expand_dims(image, axis = 0)

In [56]:
image.shape

(1, 64, 64, 3)

In [57]:
image

array([[[[157, 154, 149],
         [160, 158, 152],
         [186, 183, 178],
         ...,
         [192, 189, 184],
         [192, 189, 184],
         [189, 185, 182]],

        [[159, 156, 151],
         [165, 162, 157],
         [181, 178, 173],
         ...,
         [195, 193, 187],
         [192, 189, 184],
         [192, 188, 185]],

        [[141, 138, 133],
         [168, 165, 160],
         [174, 171, 166],
         ...,
         [183, 180, 175],
         [173, 170, 165],
         [188, 184, 181]],

        ...,

        [[189, 184, 180],
         [191, 186, 182],
         [171, 166, 162],
         ...,
         [170, 167, 162],
         [171, 169, 164],
         [208, 205, 200]],

        [[213, 208, 204],
         [216, 211, 207],
         [168, 163, 159],
         ...,
         [178, 175, 170],
         [179, 176, 171],
         [167, 164, 159]],

        [[172, 167, 163],
         [205, 200, 196],
         [174, 169, 165],
         ...,
         [180, 176, 173],
        

In [58]:
image = image / 255.0

In [59]:
image

array([[[[0.61568627, 0.60392157, 0.58431373],
         [0.62745098, 0.61960784, 0.59607843],
         [0.72941176, 0.71764706, 0.69803922],
         ...,
         [0.75294118, 0.74117647, 0.72156863],
         [0.75294118, 0.74117647, 0.72156863],
         [0.74117647, 0.7254902 , 0.71372549]],

        [[0.62352941, 0.61176471, 0.59215686],
         [0.64705882, 0.63529412, 0.61568627],
         [0.70980392, 0.69803922, 0.67843137],
         ...,
         [0.76470588, 0.75686275, 0.73333333],
         [0.75294118, 0.74117647, 0.72156863],
         [0.75294118, 0.7372549 , 0.7254902 ]],

        [[0.55294118, 0.54117647, 0.52156863],
         [0.65882353, 0.64705882, 0.62745098],
         [0.68235294, 0.67058824, 0.65098039],
         ...,
         [0.71764706, 0.70588235, 0.68627451],
         [0.67843137, 0.66666667, 0.64705882],
         [0.7372549 , 0.72156863, 0.70980392]],

        ...,

        [[0.74117647, 0.72156863, 0.70588235],
         [0.74901961, 0.72941176, 0.71372549]

In [60]:
prediction = model.predict(image)

1/1 [==============================] - 0s 167ms/step


In [61]:
prediction

array([[0.01309073]], dtype=float32)

In [62]:
prediction[0][0]

0.013090734

In [64]:
if prediction[0][0] >= 0.5:
  print("1 => positive => crack detected")
else:
  print("0 => negative => crack not detected")

0 => negative => crack not detected


In [65]:
import cv2
import numpy as np

img_path = "/content/surface-crack-detection/Positive/00003.jpg"
image = cv2.imread(img_path)
image = cv2.resize(image,(64,64))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = np.expand_dims(image, axis = 0)
image = image / 255.0
prediction = model.predict(image)
if prediction[0][0] >= 0.5:
  print("1 => positive => crack detected")
else:
  print("0 => negative => crack not detected")

1/1 [==============================] - 0s 22ms/step
1 => positive => crack detected


In [66]:
model.evaluate(xtest,ytest)

63/63 [==============================] - 3s 53ms/step - loss: 0.0363 - accuracy: 0.9900


[0.03627123683691025, 0.9900000095367432]